id: PE4842808
initial_creation_type: ocr
source_metadata:
  volumes:
    baf7f1f10d634dde922f63b85dce3631:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1682
      volume_number: 56
